### ISSUE TITLE
Push notification prompting can only be done form a user gesture

### ISSUE THREAD

**Issue by niklat22** [ankurp/Apple-Web-Push-Notification-Rails#4]
I am use safari 13 for web push notification. when it call in requestPermissions() it gives me '**Push notification prompting can only be done form a user gesture**' error.

![Screenshot 2019-11-15 at 6 16 40 PM](https://user-images.githubusercontent.com/46586998/69491010-3d632a80-0eb5-11ea-8408-aa6c8ea78f8f.png)

**Comment by niklat22** [comment]
The issue was resolved.

Reason for not add following code in manifest.json file.

`{
   ....
  "permissions": {
    "notifications"
  }
}`

**Comment by marwankhanfar** [comment]
@niklat22 can you send us the content and structure of manifest.json file
